import { AuditWithTimezone } from '@shared/models/audit.model';
import { StorageUnitStatus } from '@storage/types';
import { Column, Entity, JoinColumn, ManyToOne, PrimaryGeneratedColumn, Unique } from 'typeorm';
import { Facility } from './facility.entity';

/**
 * The rentable part of a standalone warehouse. Each facility holds exactly one live unit
 * (`UQ_storage_units_one_per_facility`); the facility carries address and coordinates,
 * the unit carries size, price, deposit and the rental lifecycle status.
 */
@Entity('storage_units')
@Unique('UQ_units_facility_code', ['facilityId', 'code'])
export class StorageUnit extends AuditWithTimezone {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'uuid', name: 'facility_id' })
  facilityId: string;

  /** Mirrors the warehouse (facility) code. */
  @Column({ length: 50 })
  code: string;

  @Column({ type: 'decimal', precision: 14, scale: 2, name: 'monthly_price' })
  monthlyPrice: number;

  @Column({ type: 'decimal', precision: 7, scale: 2, name: 'width_m' })
  widthM: number;

  @Column({ type: 'decimal', precision: 7, scale: 2, name: 'length_m' })
  lengthM: number;

  @Column({ type: 'decimal', precision: 7, scale: 2, nullable: true, name: 'height_m' })
  heightM: number | null;

  /** Generated by the database from width × length. */
  @Column({
    type: 'decimal',
    precision: 12,
    scale: 2,
    name: 'area_m2',
    generatedType: 'STORED',
    asExpression: 'round("width_m" * "length_m", 2)',
    insert: false,
    update: false,
  })
  areaM2: number;

  /** Generated by the database from width × length × height; null without a height. */
  @Column({
    type: 'decimal',
    precision: 14,
    scale: 2,
    nullable: true,
    name: 'volume_m3',
    generatedType: 'STORED',
    asExpression: 'round("width_m" * "length_m" * "height_m", 2)',
    insert: false,
    update: false,
  })
  volumeM3: number | null;

  @Column({ type: 'varchar', length: 25, default: StorageUnitStatus.AVAILABLE })
  status: StorageUnitStatus;

  @Column({ type: 'text', nullable: true })
  notes?: string;

  /** Deposit in whole months (1–12); null follows the `deposit.default_months` setting. */
  @Column({ type: 'smallint', nullable: true, name: 'deposit_months' })
  depositMonths: number | null;

  @ManyToOne(() => Facility)
  @JoinColumn({ name: 'facility_id' })
  facility: Facility;
}
