import { AuditWithTimezone } from '@shared/models/audit.model';
import { StorageUnitStatus } from '@storage/types';
import { Column, Entity, Index, JoinColumn, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { Facility } from './facility.entity';

/** A photo of the warehouse; `fileKey` is an `uploads/` object key in the private bucket. */
export interface WarehouseImage {
  fileKey: string;
  name: string;
  mimeType: string;
  size?: number;
}

/**
 * A rentable warehouse belonging to a facility (branch). It carries its own name, address,
 * coordinates, size, price, deposit and rental lifecycle status.
 */
@Entity('storage_units')
@Index('UQ_storage_units_code', ['code'], { unique: true, where: '"deleted_at" IS NULL' })
@Index('IDX_storage_units_facility', ['facilityId'])
export class StorageUnit extends AuditWithTimezone {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'uuid', name: 'facility_id' })
  facilityId: string;

  /** Globally unique among live warehouses. */
  @Column({ length: 50 })
  code: string;

  @Column({ length: 150 })
  name: string;

  @Column({ length: 255, name: 'address_line' })
  addressLine: string;

  /** Ward code — FK → wards.code (VN post-2025 two-level model) */
  @Column({ type: 'varchar', length: 20, nullable: true, name: 'ward_code' })
  wardCode?: string | null;

  /** Province code — FK → provinces.code */
  @Column({ type: 'varchar', length: 20, nullable: true, name: 'province_code' })
  provinceCode?: string | null;

  @Column({ type: 'decimal', precision: 9, scale: 6 })
  latitude: number;

  @Column({ type: 'decimal', precision: 9, scale: 6 })
  longitude: number;

  @Column({ type: 'decimal', precision: 14, scale: 2, name: 'monthly_price' })
  monthlyPrice: number;

  @Column({ type: 'decimal', precision: 7, scale: 2, name: 'width_m' })
  widthM: number;

  @Column({ type: 'decimal', precision: 7, scale: 2, name: 'length_m' })
  lengthM: number;

  @Column({ type: 'decimal', precision: 7, scale: 2, nullable: true, name: 'height_m' })
  heightM: number | null;

  /** Generated by the database from width × length. */
  @Column({
    type: 'decimal',
    precision: 12,
    scale: 2,
    name: 'area_m2',
    generatedType: 'STORED',
    asExpression: 'round("width_m" * "length_m", 2)',
    insert: false,
    update: false,
  })
  areaM2: number;

  /** Generated by the database from width × length × height; null without a height. */
  @Column({
    type: 'decimal',
    precision: 14,
    scale: 2,
    nullable: true,
    name: 'volume_m3',
    generatedType: 'STORED',
    asExpression: 'round("width_m" * "length_m" * "height_m", 2)',
    insert: false,
    update: false,
  })
  volumeM3: number | null;

  @Column({ type: 'varchar', length: 25, default: StorageUnitStatus.AVAILABLE })
  status: StorageUnitStatus;

  @Column({ type: 'text', nullable: true })
  notes?: string;

  /** Deposit in whole months (1–12); null follows the `deposit.default_months` setting. */
  @Column({ type: 'smallint', nullable: true, name: 'deposit_months' })
  depositMonths: number | null;

  /** Photos shown to customers, in display order; the first one is the cover. */
  @Column({ type: 'jsonb', default: () => "'[]'" })
  images: WarehouseImage[];

  @ManyToOne(() => Facility)
  @JoinColumn({ name: 'facility_id' })
  facility: Facility;
}
