export const ENV_KEY = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_DATABASE: 'DB_DATABASE',
  DB_SYNCHRONIZE: 'DB_SYNCHRONIZE',
  DB_LOGGING: 'DB_LOGGING',
  DB_SSL: 'DB_SSL',
  ENABLE_SWAGGER: 'ENABLE_SWAGGER',
  ENABLE_CORS: 'ENABLE_CORS',

  // S3-compatible object storage (e.g. Cloudflare R2)
  S3_ENDPOINT: 'S3_ENDPOINT',
  S3_REGION: 'S3_REGION',
  S3_ACCESS_KEY: 'S3_ACCESS_KEY',
  S3_SECRET_KEY: 'S3_SECRET_KEY',
  S3_BUCKET: 'S3_BUCKET',
  S3_FORCE_PATH_STYLE: 'S3_FORCE_PATH_STYLE',
  S3_PUBLIC_URL: 'S3_PUBLIC_URL',
} as const;
