import {
  ContractStatus,
  IAuditLog,
  IFacility,
  IInspectionRecord,
  IKeyInventoryItem,
  IPaymentRecord,
  IPermissionTemplate,
  IPromotionCoupon,
  IRentalContract,
  IShiftHandoverNote,
  IStaffMember,
  IStorageUnit,
  IWaitlistEntry,
  UnitSizeCategory,
  UnitStatus,
} from './self-storage';

export const MOCK_FACILITIES: IFacility[] = [
  {
    id: 'fac-sg-01',
    code: 'SH-SALA',
    name: 'StorageHub Sala Mega Center',
    address: '10 Mai Chí Thọ, P. An Lợi Đông, TP. Thủ Đức, TP. Hồ Chí Minh',
    city: 'TP. Hồ Chí Minh',
    district: 'TP. Thủ Đức',
    phone: '028 7300 8899',
    managerName: 'Nguyễn Quốc Bảo',
    totalUnits: 180,
    occupiedUnits: 156,
    availableUnits: 18,
    occupancyRate: 86.6,
    zones: [
      'Khu A - Mini Locker',
      'Khu B - Standard Room',
      'Khu C - Climate Cold',
      'Khu D - Large Warehouse',
    ],
    amenities: [
      'Bảo vệ 24/7',
      'Điều hòa 22-25°C',
      'CCTV full HD',
      'Thang máy nâng hàng 2 tấn',
      'Đậu xe tải tận cửa',
      'Hệ thống PCCC tự động FM200',
    ],
    operatingHours: '06:00 - 23:00 hàng ngày (Truy cập thẻ từ 24/7)',
    imageUrl:
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    isFavorite: true,
  },
  {
    id: 'fac-hn-01',
    code: 'SH-TIMES',
    name: 'StorageHub Times City Park',
    address: '458 Minh Khai, P. Vĩnh Tuy, Q. Hai Bà Trưng, Hà Nội',
    city: 'Hà Nội',
    district: 'Hai Bà Trưng',
    phone: '024 7100 9988',
    managerName: 'Trần Đình Trọng',
    totalUnits: 120,
    occupiedUnits: 108,
    availableUnits: 8,
    occupancyRate: 90.0,
    zones: ['Zone 1 - Hầm B2', 'Zone 2 - Tầng Lửng', 'Zone 3 - Kho Quần áo'],
    amenities: [
      'CCTV 24/7',
      'Kiểm soát ẩm < 50%',
      'Xe đẩy hàng miễn phí',
      'Mã PIN bảo mật 2 lớp',
      'Bảo hiểm cháy nổ',
    ],
    operatingHours: 'Truy cập thông minh 24/7 bằng Smart QR',
    imageUrl:
      'https://images.unsplash.com/photo-1590247813693-5541d1c609fd?auto=format&fit=crop&w=800&q=80',
    isFavorite: false,
  },
  {
    id: 'fac-dn-01',
    code: 'SH-HAICHAU',
    name: 'StorageHub Đà Nẵng Riverside',
    address: '228 Đường 2 Tháng 9, P. Hòa Cường Bắc, Q. Hải Châu, Đà Nẵng',
    city: 'Đà Nẵng',
    district: 'Hải Châu',
    phone: '0236 730 6677',
    managerName: 'Lê Hoàng Yến',
    totalUnits: 65,
    occupiedUnits: 46,
    availableUnits: 16,
    occupancyRate: 70.8,
    zones: ['Khu Trệt - Kho Hàng', 'Khu Lầu 1 - Tủ đồ cá nhân'],
    amenities: ['Camera an ninh', 'Khóa từ RFID', 'Bãi đỗ ô tô', 'Dịch vụ đóng gói'],
    operatingHours: '07:30 - 21:30 (Mở cửa cuối tuần)',
    imageUrl:
      'https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=800&q=80',
    isFavorite: true,
  },
];

export const MOCK_UNITS: IStorageUnit[] = [
  // Zone A - Mini Locker
  {
    id: 'u-a101',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    code: 'A-101',
    zone: 'Khu A - Mini Locker',
    floor: 1,
    category: UnitSizeCategory.LOCKER,
    categoryLabel: 'Locker Cá Nhân (1.5 m³)',
    dimensions: { lengthM: 1.0, widthM: 1.0, heightM: 1.5 },
    areaM2: 1.0,
    volumeM3: 1.5,
    pricePerMonth: 450000,
    depositAmount: 450000,
    status: UnitStatus.OCCUPIED,
    currentRenter: {
      name: 'Vũ Minh Tuấn',
      phone: '0903 112 445',
      email: 'tuan.vm@gmail.com',
      contractCode: 'HD-2026-0018',
      startDate: '2026-01-15',
      endDate: '2026-07-15',
    },
    features: ['Khóa số điện tử', 'Để vừa 4 vali lớn hoặc 8 thùng carton'],
  },
  {
    id: 'u-a102',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    code: 'A-102',
    zone: 'Khu A - Mini Locker',
    floor: 1,
    category: UnitSizeCategory.LOCKER,
    categoryLabel: 'Locker Cá Nhân (1.5 m³)',
    dimensions: { lengthM: 1.0, widthM: 1.0, heightM: 1.5 },
    areaM2: 1.0,
    volumeM3: 1.5,
    pricePerMonth: 450000,
    depositAmount: 450000,
    status: UnitStatus.AVAILABLE,
    features: ['Khóa số điện tử', 'Thích hợp lưu hồ sơ, đồ du lịch'],
  },
  {
    id: 'u-a103',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    code: 'A-103',
    zone: 'Khu A - Mini Locker',
    floor: 1,
    category: UnitSizeCategory.LOCKER,
    categoryLabel: 'Locker Cá Nhân (1.5 m³)',
    dimensions: { lengthM: 1.0, widthM: 1.0, heightM: 1.5 },
    areaM2: 1.0,
    volumeM3: 1.5,
    pricePerMonth: 450000,
    depositAmount: 450000,
    status: UnitStatus.RESERVED,
    currentRenter: {
      name: 'Ngô Thanh Hằng',
      phone: '0918 882 119',
      email: 'hang.ngo@yahoo.com',
      contractCode: 'RES-2026-0094',
      startDate: '2026-09-25',
      endDate: '2026-12-25',
    },
    features: ['Khóa số điện tử'],
  },
  {
    id: 'u-a104',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    code: 'A-104',
    zone: 'Khu A - Mini Locker',
    floor: 1,
    category: UnitSizeCategory.LOCKER,
    categoryLabel: 'Locker Cá Nhân (1.5 m³)',
    dimensions: { lengthM: 1.0, widthM: 1.0, heightM: 1.5 },
    areaM2: 1.0,
    volumeM3: 1.5,
    pricePerMonth: 450000,
    depositAmount: 450000,
    status: UnitStatus.AVAILABLE,
    features: ['Khóa số điện tử'],
  },
  {
    id: 'u-a105',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    code: 'A-105',
    zone: 'Khu A - Mini Locker',
    floor: 1,
    category: UnitSizeCategory.LOCKER,
    categoryLabel: 'Locker Cá Nhân (1.5 m³)',
    dimensions: { lengthM: 1.0, widthM: 1.0, heightM: 1.5 },
    areaM2: 1.0,
    volumeM3: 1.5,
    pricePerMonth: 450000,
    depositAmount: 450000,
    status: UnitStatus.OVERDUE,
    currentRenter: {
      name: 'Lý Kiến Quốc',
      phone: '0983 999 102',
      email: 'kienquoc.ly@gmail.com',
      contractCode: 'HD-2026-0004',
      startDate: '2026-03-01',
      endDate: '2026-09-01',
    },
    features: ['Khóa số điện tử'],
    notes: 'Quá hạn trả kho 21 ngày, đã gọi nhắc nhở 3 lần.',
  },

  // Zone B - Standard Room
  {
    id: 'u-b201',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    code: 'B-201',
    zone: 'Khu B - Standard Room',
    floor: 2,
    category: UnitSizeCategory.STANDARD,
    categoryLabel: 'Kho Tiêu Chuẩn (12.5 m³)',
    dimensions: { lengthM: 2.5, widthM: 2.0, heightM: 2.5 },
    areaM2: 5.0,
    volumeM3: 12.5,
    pricePerMonth: 1850000,
    depositAmount: 1850000,
    status: UnitStatus.OCCUPIED,
    currentRenter: {
      name: 'Phạm Hồng Ánh',
      phone: '0977 345 889',
      email: 'honganh.decor@gmail.com',
      contractCode: 'HD-2026-0045',
      startDate: '2026-02-10',
      endDate: '2026-10-10',
    },
    features: ['Cửa cuộn thép chống cháy', 'Để vừa nội thất căn hộ 1 phòng ngủ, xe máy, sofa'],
  },
  {
    id: 'u-b202',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    code: 'B-202',
    zone: 'Khu B - Standard Room',
    floor: 2,
    category: UnitSizeCategory.STANDARD,
    categoryLabel: 'Kho Tiêu Chuẩn (12.5 m³)',
    dimensions: { lengthM: 2.5, widthM: 2.0, heightM: 2.5 },
    areaM2: 5.0,
    volumeM3: 12.5,
    pricePerMonth: 1850000,
    depositAmount: 1850000,
    status: UnitStatus.AVAILABLE,
    features: ['Cửa cuộn thép chống cháy', 'Cảm biến chuyển động bật đèn'],
  },
  {
    id: 'u-b203',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    code: 'B-203',
    zone: 'Khu B - Standard Room',
    floor: 2,
    category: UnitSizeCategory.STANDARD,
    categoryLabel: 'Kho Tiêu Chuẩn (12.5 m³)',
    dimensions: { lengthM: 2.5, widthM: 2.0, heightM: 2.5 },
    areaM2: 5.0,
    volumeM3: 12.5,
    pricePerMonth: 1850000,
    depositAmount: 1850000,
    status: UnitStatus.OCCUPIED,
    currentRenter: {
      name: 'Startup Cát Tường Logistics',
      phone: '0934 556 789',
      email: 'ops@cattuong.vn',
      contractCode: 'HD-2026-0051',
      startDate: '2026-04-01',
      endDate: '2027-04-01',
    },
    features: ['Cửa cuộn thép chống cháy'],
  },
  {
    id: 'u-b204',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    code: 'B-204',
    zone: 'Khu B - Standard Room',
    floor: 2,
    category: UnitSizeCategory.STANDARD,
    categoryLabel: 'Kho Tiêu Chuẩn (12.5 m³)',
    dimensions: { lengthM: 2.5, widthM: 2.0, heightM: 2.5 },
    areaM2: 5.0,
    volumeM3: 12.5,
    pricePerMonth: 1850000,
    depositAmount: 1850000,
    status: UnitStatus.MAINTENANCE,
    features: ['Cửa cuộn thép chống cháy'],
    notes: 'Đang thay thế ray trượt cửa cuốn và sơn dặm lại sàn.',
  },

  // Zone C - Climate Cold
  {
    id: 'u-c301',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    code: 'C-301',
    zone: 'Khu C - Climate Cold',
    floor: 3,
    category: UnitSizeCategory.CLIMATE_CONTROLLED,
    categoryLabel: 'Kho Kiểm Soát Nhiệt Ẩm (8 m³)',
    dimensions: { lengthM: 2.0, widthM: 1.6, heightM: 2.5 },
    areaM2: 3.2,
    volumeM3: 8.0,
    pricePerMonth: 2400000,
    depositAmount: 2400000,
    status: UnitStatus.OCCUPIED,
    isClimateControlled: true,
    currentRenter: {
      name: 'Trịnh Hoàng Long',
      phone: '0912 345 678',
      email: 'long.winecellar@gmail.com',
      contractCode: 'HD-2026-0072',
      startDate: '2026-05-01',
      endDate: '2027-05-01',
    },
    features: [
      'Nhiệt độ ổn định 18-20°C',
      'Độ ẩm 55%',
      'Bảo quản rượu vang, đồ da cao cấp, tranh nghệ thuật',
    ],
  },
  {
    id: 'u-c302',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    code: 'C-302',
    zone: 'Khu C - Climate Cold',
    floor: 3,
    category: UnitSizeCategory.CLIMATE_CONTROLLED,
    categoryLabel: 'Kho Kiểm Soát Nhiệt Ẩm (8 m³)',
    dimensions: { lengthM: 2.0, widthM: 1.6, heightM: 2.5 },
    areaM2: 3.2,
    volumeM3: 8.0,
    pricePerMonth: 2400000,
    depositAmount: 2400000,
    status: UnitStatus.AVAILABLE,
    isClimateControlled: true,
    features: ['Nhiệt độ ổn định 18-20°C', 'Độ ẩm 55%', 'Cảm biến IoT báo động nhiệt qua SMS'],
  },

  // Zone D - Large Warehouse
  {
    id: 'u-d401',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    code: 'D-401',
    zone: 'Khu D - Large Warehouse',
    floor: 1,
    category: UnitSizeCategory.LARGE,
    categoryLabel: 'Kho Hàng Lớn Doanh Nghiệp (30 m³)',
    dimensions: { lengthM: 4.0, widthM: 3.0, heightM: 2.5 },
    areaM2: 12.0,
    volumeM3: 30.0,
    pricePerMonth: 4200000,
    depositAmount: 4200000,
    status: UnitStatus.OCCUPIED,
    currentRenter: {
      name: 'Công ty TNHH Thời Trang An Nam',
      phone: '0908 776 543',
      email: 'warehouse@annamfashion.com',
      contractCode: 'HD-2026-0011',
      startDate: '2025-11-01',
      endDate: '2026-11-01',
    },
    features: ['Xe nâng vào tận kho', 'Tải trọng sàn 1500kg/m²', 'Kệ chứa hàng lắp sẵn 4 tầng'],
  },
  {
    id: 'u-d402',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    code: 'D-402',
    zone: 'Khu D - Large Warehouse',
    floor: 1,
    category: UnitSizeCategory.LARGE,
    categoryLabel: 'Kho Hàng Lớn Doanh Nghiệp (30 m³)',
    dimensions: { lengthM: 4.0, widthM: 3.0, heightM: 2.5 },
    areaM2: 12.0,
    volumeM3: 30.0,
    pricePerMonth: 4200000,
    depositAmount: 4200000,
    status: UnitStatus.AVAILABLE,
    features: ['Xe nâng vào tận kho', 'Tải trọng sàn 1500kg/m²', 'Điện 3 pha sẵn sàng'],
  },
];

export const MOCK_CONTRACTS: IRentalContract[] = [
  {
    id: 'ctr-001',
    contractCode: 'HD-2026-0045',
    unitId: 'u-b201',
    unitCode: 'B-201',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    customerName: 'Phạm Hồng Ánh',
    customerPhone: '0977 345 889',
    customerEmail: 'honganh.decor@gmail.com',
    startDate: '2026-02-10',
    endDate: '2026-10-10',
    monthlyRent: 1850000,
    depositAmount: 1850000,
    status: ContractStatus.EXPIRING_SOON,
    qrPassCode: 'QR-PASS-B201-9921',
    pinCode: '7842',
    assignedAccessCardId: 'CARD-SG-018',
    assignedKeyId: 'KEY-B201',
    autoRenew: true,
    createdAt: '2026-02-08',
  },
  {
    id: 'ctr-002',
    contractCode: 'HD-2026-0004',
    unitId: 'u-a105',
    unitCode: 'A-105',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    customerName: 'Lý Kiến Quốc',
    customerPhone: '0983 999 102',
    customerEmail: 'kienquoc.ly@gmail.com',
    startDate: '2026-03-01',
    endDate: '2026-09-01',
    monthlyRent: 450000,
    depositAmount: 450000,
    status: ContractStatus.OVERDUE,
    qrPassCode: 'QR-PASS-A105-1102',
    pinCode: '1099',
    assignedAccessCardId: 'CARD-SG-004',
    autoRenew: false,
    notes: 'Quá hạn trả kho 21 ngày, phong tỏa truy cập thẻ từ.',
    createdAt: '2026-02-28',
  },
  {
    id: 'ctr-003',
    contractCode: 'RES-2026-0094',
    unitId: 'u-a103',
    unitCode: 'A-103',
    facilityId: 'fac-sg-01',
    facilityName: 'StorageHub Sala Mega Center',
    customerName: 'Ngô Thanh Hằng',
    customerPhone: '0918 882 119',
    customerEmail: 'hang.ngo@yahoo.com',
    startDate: '2026-09-25',
    endDate: '2026-12-25',
    monthlyRent: 450000,
    depositAmount: 450000,
    status: ContractStatus.PENDING_HANDOVER,
    qrPassCode: 'QR-PASS-A103-8831',
    pinCode: '3419',
    autoRenew: false,
    createdAt: '2026-09-20',
  },
];

export const MOCK_PAYMENTS: IPaymentRecord[] = [
  {
    id: 'pay-001',
    contractCode: 'HD-2026-0045',
    customerName: 'Phạm Hồng Ánh',
    amount: 1850000,
    type: 'RENT',
    method: 'VNPAY',
    status: 'PAID',
    paidAt: '2026-09-10 14:22',
    invoiceUrl: '/invoices/INV-2026-0941.pdf',
  },
  {
    id: 'pay-002',
    contractCode: 'RES-2026-0094',
    customerName: 'Ngô Thanh Hằng',
    amount: 450000,
    type: 'DEPOSIT',
    method: 'MOMO',
    status: 'PAID',
    paidAt: '2026-09-20 09:15',
    invoiceUrl: '/invoices/INV-2026-0988.pdf',
  },
  {
    id: 'pay-003',
    contractCode: 'HD-2026-0011',
    customerName: 'Công ty TNHH Thời Trang An Nam',
    amount: 4200000,
    type: 'RENT',
    method: 'BANK_TRANSFER',
    status: 'PAID',
    paidAt: '2026-09-01 10:00',
    invoiceUrl: '/invoices/INV-2026-0890.pdf',
  },
];

export const MOCK_WAITLIST: IWaitlistEntry[] = [
  {
    id: 'wl-01',
    customerName: 'Hoàng Văn Thắng',
    customerPhone: '0909 234 567',
    facilityId: 'fac-sg-01',
    preferredCategory: UnitSizeCategory.CLIMATE_CONTROLLED,
    desiredStartDate: '2026-10-01',
    createdAt: '2026-09-18 16:30',
    status: 'WAITING',
  },
  {
    id: 'wl-02',
    customerName: 'Studio Nhiếp Ảnh Sài Gòn',
    customerPhone: '0913 444 888',
    facilityId: 'fac-sg-01',
    preferredCategory: UnitSizeCategory.STANDARD,
    desiredStartDate: '2026-09-28',
    createdAt: '2026-09-19 11:20',
    status: 'OFFERED',
  },
];

export const MOCK_INSPECTIONS: IInspectionRecord[] = [
  {
    id: 'insp-01',
    unitCode: 'B-201',
    facilityId: 'fac-sg-01',
    staffName: 'Lê Minh Quân (Staff Ca Sáng)',
    type: 'HANDOVER',
    cleanlinessScore: 5,
    hasDamage: false,
    damageFine: 0,
    photoUrls: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=400&q=80',
    ],
    customerSignature: 'Phạm Hồng Ánh',
    staffSignature: 'Lê Minh Quân',
    inspectedAt: '2026-02-10 10:15',
    status: 'PASSED',
  },
  {
    id: 'insp-02',
    unitCode: 'B-204',
    facilityId: 'fac-sg-01',
    staffName: 'Đặng Tuấn Kiệt (Staff Ca Chiều)',
    type: 'RETURN',
    cleanlinessScore: 2,
    hasDamage: true,
    damageDescription: 'Cửa trượt bị móp nặng do va đập thùng hàng xe tải, sàn dính vết dầu loang.',
    damageFine: 750000,
    photoUrls: [
      'https://images.unsplash.com/photo-1590247813693-5541d1c609fd?auto=format&fit=crop&w=400&q=80',
    ],
    customerSignature: 'Nguyễn Văn Đạt',
    staffSignature: 'Đặng Tuấn Kiệt',
    inspectedAt: '2026-09-21 16:45',
    status: 'FAILED_WITH_PENALTY',
  },
];

export const MOCK_KEY_INVENTORY: IKeyInventoryItem[] = [
  {
    id: 'key-01',
    code: 'CARD-SG-001',
    type: 'ACCESS_CARD',
    facilityId: 'fac-sg-01',
    assignedUnitCode: 'A-101',
    status: 'ASSIGNED',
    lastCheckedAt: '2026-09-20',
  },
  {
    id: 'key-02',
    code: 'CARD-SG-002',
    type: 'ACCESS_CARD',
    facilityId: 'fac-sg-01',
    status: 'IN_STOCK',
    lastCheckedAt: '2026-09-22',
  },
  {
    id: 'key-03',
    code: 'PADLOCK-SG-088',
    type: 'SMART_PADLOCK',
    facilityId: 'fac-sg-01',
    status: 'IN_STOCK',
    lastCheckedAt: '2026-09-22',
  },
  {
    id: 'key-04',
    code: 'KEY-SG-D401',
    type: 'PHYSICAL_KEY',
    facilityId: 'fac-sg-01',
    assignedUnitCode: 'D-401',
    status: 'ASSIGNED',
    lastCheckedAt: '2026-09-15',
  },
];

export const MOCK_SHIFT_NOTES: IShiftHandoverNote[] = [
  {
    id: 'shift-01',
    facilityId: 'fac-sg-01',
    fromStaffName: 'Lê Minh Quân',
    toStaffName: 'Đặng Tuấn Kiệt',
    shift: 'SÁNG (07:00 - 15:00)',
    date: '2026-09-22',
    keySummary:
      'Ca sáng diễn ra thuận lợi, đã hoàn thành 4 lượt check-in và 1 lượt bàn giao chìa kho C-301.',
    pendingTasks: [
      'Khách hẹn trả kho B-204 lúc 16:30, cần kiểm tra kỹ vết móp cửa cuốn.',
      'Khách Ngô Thanh Hằng dự kiến 17:00 đến nhận thẻ từ kho A-103.',
    ],
    resolvedIssues: [
      'Đã thay pin khóa cảm ứng dãy A.',
      'Đã cấp thêm 10 thùng carton cho khách quầy lễ tân.',
    ],
    urgentAlerts: 'Lưu ý kiểm tra van PCCC Zone C lúc 19:00 theo lịch bảo trì.',
  },
];

export const MOCK_STAFF: IStaffMember[] = [
  {
    id: 'st-01',
    name: 'Lê Minh Quân',
    role: 'Nhân viên lễ tân & Bàn giao',
    facilityId: 'fac-sg-01',
    shift: 'Ca Sáng (07:00 - 15:00)',
    avatarUrl:
      'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80',
    activeTasksCount: 2,
    completedTodayCount: 6,
    performanceScore: 98,
  },
  {
    id: 'st-02',
    name: 'Đặng Tuấn Kiệt',
    role: 'Kỹ thuật viên & Kiểm tra kho',
    facilityId: 'fac-sg-01',
    shift: 'Ca Chiều (14:30 - 22:30)',
    avatarUrl:
      'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&q=80',
    activeTasksCount: 4,
    completedTodayCount: 3,
    performanceScore: 94,
  },
  {
    id: 'st-03',
    name: 'Nguyễn Văn Thái',
    role: 'An ninh & Trực ca đêm',
    facilityId: 'fac-sg-01',
    shift: 'Ca Đêm (22:00 - 07:00)',
    avatarUrl:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80',
    activeTasksCount: 0,
    completedTodayCount: 5,
    performanceScore: 96,
  },
];

export const MOCK_AUDIT_LOGS: IAuditLog[] = [
  {
    id: 'log-001',
    timestamp: '2026-09-22 08:45:12',
    actorName: 'Nguyễn Quốc Bảo (Facility Manager)',
    actorRole: 'FACILITY_MANAGER',
    action: 'AUTO_ASSIGN_UNIT',
    target: 'Unit A-103 -> Ngô Thanh Hằng',
    facilityName: 'StorageHub Sala Mega Center',
    ipAddress: '118.69.182.45',
    details: 'Hệ thống tự động gán Unit A-103 cho reservation #RES-2026-0094.',
  },
  {
    id: 'log-002',
    timestamp: '2026-09-22 08:30:00',
    actorName: 'Trần Minh Tâm (Operations Manager)',
    actorRole: 'OPERATIONS_MANAGER',
    action: 'UPDATE_PRICING_POLICY',
    target: 'Chính sách quá hạn trễ hạn thanh toán',
    facilityName: 'Toàn hệ thống',
    ipAddress: '14.161.22.10',
    details: 'Cập nhật phí phạt trễ hạn từ 2% lên 2.5%/ngày quá hạn sau ngày thứ 5.',
  },
  {
    id: 'log-003',
    timestamp: '2026-09-21 16:48:33',
    actorName: 'Đặng Tuấn Kiệt (Facility Staff)',
    actorRole: 'FACILITY_STAFF',
    action: 'RECORD_DAMAGE_INSPECTION',
    target: 'Unit B-204 (Return Inspection)',
    facilityName: 'StorageHub Sala Mega Center',
    ipAddress: '172.16.10.4',
    details: 'Ghi nhận móp cửa cuốn, áp dụng cấn trừ cọc 750,000 VNĐ.',
  },
  {
    id: 'log-004',
    timestamp: '2026-09-21 10:12:05',
    actorName: 'Admin Tổng (Root Admin)',
    actorRole: 'ADMIN',
    action: 'CREATE_PERMISSION_TEMPLATE',
    target: 'Template: Kế toán Chi nhánh',
    ipAddress: '113.190.234.12',
    details: 'Tạo mẫu phân quyền mới áp dụng cho bộ phận tài chính các cơ sở.',
  },
];

export const MOCK_PERMISSION_TEMPLATES: IPermissionTemplate[] = [
  {
    id: 'tmpl-01',
    name: 'Quản lý cơ sở tiêu chuẩn (Standard Facility Manager)',
    description:
      'Toàn quyền điều hành tại cơ sở: gán kho, phân công nhân viên, xử lý cọc và duyệt bảo trì.',
    userCount: 8,
    permissions: {
      canViewFinancials: true,
      canApproveRefund: true,
      canAssignUnits: true,
      canModifyPricing: false,
      canInspectUnits: true,
      canManageStaff: true,
      canViewSystemLogs: false,
    },
  },
  {
    id: 'tmpl-02',
    name: 'Nhân viên lễ tân & Bàn giao (Front Desk Staff)',
    description:
      'Thực hiện check-in/out bằng QR, lập biên bản bàn giao, cấp thẻ từ và hỗ trợ khách.',
    userCount: 24,
    permissions: {
      canViewFinancials: false,
      canApproveRefund: false,
      canAssignUnits: false,
      canModifyPricing: false,
      canInspectUnits: true,
      canManageStaff: false,
      canViewSystemLogs: false,
    },
  },
  {
    id: 'tmpl-03',
    name: 'Kỹ thuật viên hiện trường (Maintenance & Inspection)',
    description:
      'Chụp ảnh nghiệm thu hiện trường, cập nhật trạng thái kho bảo trì, kiểm kê ổ khóa/thẻ.',
    userCount: 14,
    permissions: {
      canViewFinancials: false,
      canApproveRefund: false,
      canAssignUnits: false,
      canModifyPricing: false,
      canInspectUnits: true,
      canManageStaff: false,
      canViewSystemLogs: false,
    },
  },
];

export const MOCK_PROMOTIONS: IPromotionCoupon[] = [
  {
    id: 'promo-01',
    code: 'STORAGE-NEW20',
    description: 'Giảm 20% tháng thuê đầu tiên cho khách hàng cá nhân mới.',
    discountPercent: 20,
    minRentalMonths: 3,
    facilityScope: 'Tất cả cơ sở',
    validUntil: '2026-12-31',
    usageCount: 142,
    isActive: true,
  },
  {
    id: 'promo-02',
    code: 'SALA-MEGA30',
    description: 'Ưu đãi 30% cho hợp đồng thuê kho doanh nghiệp từ 6 tháng tại Sala.',
    discountPercent: 30,
    minRentalMonths: 6,
    facilityScope: 'StorageHub Sala Mega Center',
    validUntil: '2026-10-31',
    usageCount: 28,
    isActive: true,
  },
];
